#!/bin/sh
#
IMAGEDIR="$1"
BR_ROOT=$PWD

SRC_CONFIG_TXT="${PWD}/board/renga/firmware/config.txt"
DST_CONFIG_TXT="${IMAGEDIR}/rpi-firmware/config.txt"
if [ ! -f "${SRC_CONFIG_TXT}" ]; then
    : noop
elif [ ! -f "${DST_CONFIG_TXT}" ]; then
    : noop
else
    cp "${SRC_CONFIG_TXT}" "${DST_CONFIG_TXT}"
fi

exit 0
